# Generated by Django 3.1.7 on 2021-04-06 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nguoi_dung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='ma_xac_thuc',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Mã xác thực'),
        ),
    ]
