# Generated by Django 4.2.9 on 2024-01-04 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid
import weddings.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonateBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tiêu đề hình ảnh"),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Mã QR",
                    ),
                ),
                (
                    "qr_code_url",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="URL qr code",
                    ),
                ),
                (
                    "background_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Ảnh nền cho QR mới",
                    ),
                ),
                (
                    "logo_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Ảnh logo cho QR mới",
                    ),
                ),
                (
                    "new_qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Mã QR mới",
                    ),
                ),
                (
                    "new_qr_code_with_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Mã QR mới có logo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Thông tin mừng cưới",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ho_va_ten",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                (
                    "ten_rut_gon",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên rút gọn",
                    ),
                ),
                (
                    "ten_viet_tat",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên viết tắt",
                    ),
                ),
                (
                    "ten_thay_the",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên thay thế",
                    ),
                ),
                (
                    "ngay_sinh",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("NAM", "Nam"), ("NU", "Nữ")],
                        default="NU",
                        max_length=3,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "gioi_thieu",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Giới thiệu về bản thân",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Link facebook cá nhân",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "loi_nhan_gui",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lời nhắn gửi tới người tham gia",
                    ),
                ),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "kha_nang_tham_gia",
                    models.BooleanField(
                        default=False, verbose_name="Khả năng tham gia"
                    ),
                ),
                (
                    "url_invitation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Đường dẫn hình ảnh thiệp mời",
                    ),
                ),
                (
                    "donated_value",
                    models.IntegerField(default=0, verbose_name="Số tiền mừng"),
                ),
                (
                    "donate_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donate_box",
                        to="weddings.donatebox",
                        verbose_name="Mừng cưới",
                    ),
                ),
                (
                    "nguoi_lien_quan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weddings.person",
                        verbose_name="Người liên quan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Người tham gia",
                "ordering": ["ho_va_ten"],
            },
        ),
        migrations.CreateModel(
            name="PersonGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_nhom", models.CharField(max_length=255, verbose_name="Tên nhóm")),
            ],
            options={
                "verbose_name_plural": "Nhóm người tham gia",
                "ordering": ["ten_nhom"],
            },
        ),
        migrations.CreateModel(
            name="PhotoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten", models.CharField(max_length=255, verbose_name="Tên phân loại")),
                ("code", models.CharField(max_length=50, verbose_name="Mã phân loại")),
            ],
            options={
                "verbose_name_plural": "Phân loại hình ảnh",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tên mối quan hệ"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Mã mối quan hệ",
                    ),
                ),
                (
                    "chi_tiet",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chi tiết mối quan hệ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mối quan hệ",
                "ordering": ["ten"],
            },
        ),
        migrations.CreateModel(
            name="Wedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hinh_nen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình nền",
                    ),
                ),
                ("ngay_to_chuc", models.DateField(verbose_name="Ngày tổ chức lễ cưới")),
                (
                    "thong_bao",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Thông báo lễ cưới",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_sm",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Logo SM",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình xem trước khi chia sẻ (1200x630)",
                    ),
                ),
                (
                    "preview_image_type",
                    models.CharField(
                        blank=True,
                        default="image/jpeg",
                        max_length=30,
                        null=True,
                        verbose_name="Định dạng hình ảnh (image/jpeg)",
                    ),
                ),
                (
                    "description_share",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Mô tả ngắn khi chia sẻ. 2 - 4 câu",
                    ),
                ),
                (
                    "hinh_nen_loi_chuc",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình nền lời chúc",
                    ),
                ),
                (
                    "duong_dan_youtube",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Đường dẫn video youtube",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Đường dẫn rút gọn",
                    ),
                ),
                (
                    "chu_re",
                    models.ForeignKey(
                        limit_choices_to={"gioi_tinh": "NAM"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chu_re",
                        to="weddings.person",
                        verbose_name="Chú rể",
                    ),
                ),
                (
                    "co_dau",
                    models.ForeignKey(
                        limit_choices_to={"gioi_tinh": "NU"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co_dau",
                        to="weddings.person",
                        verbose_name="Cô dâu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lễ cưới",
                "ordering": ["ngay_to_chuc"],
            },
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên người gửi"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Link facebook",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=1000, verbose_name="Nội dung lời chúc"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weddings.wedding",
                        verbose_name="Lễ cưới",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lời chúc",
            },
        ),
        migrations.CreateModel(
            name="PhotosZip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tên file"
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="zip_files/",
                        verbose_name="File zip",
                    ),
                ),
                (
                    "is_extracted",
                    models.BooleanField(default=False, verbose_name="Đã giải nén"),
                ),
                (
                    "gioi_thieu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Giới thiệu về hình ảnh",
                    ),
                ),
                (
                    "phan_loai",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zip_phan_loai",
                        to="weddings.phototype",
                        verbose_name="Phân loại ảnh",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weddings.wedding",
                        verbose_name="Lễ cưới",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ảnh nén",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tiêu đề hình ảnh"),
                ),
                (
                    "gioi_thieu",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Giới thiệu về hình ảnh",
                    ),
                ),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "is_slide",
                    models.BooleanField(default=False, verbose_name="Ảnh trong slider"),
                ),
                (
                    "phan_loai",
                    models.ManyToManyField(
                        blank=True,
                        related_name="phan_loai_anh",
                        to="weddings.phototype",
                        verbose_name="Phân loại ảnh",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weddings.wedding",
                        verbose_name="Lễ cưới",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hình ảnh đám cưới",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="weddings.relationship",
                verbose_name="Mối quan hệ",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="ten_nhom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weddings.persongroup",
                verbose_name="Tên nhóm",
            ),
        ),
        migrations.CreateModel(
            name="LoveStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tên mẩu chuyện"),
                ),
                ("ngay_ky_niem", models.DateField(verbose_name="Ngày kỷ niệm")),
                (
                    "noi_dung",
                    models.CharField(
                        max_length=255, verbose_name="Nội dung mẩu chuyện"
                    ),
                ),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weddings.wedding",
                        verbose_name="Lễ cưới",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chuyện tình yêu",
                "ordering": ["ngay_ky_niem"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, verbose_name="uid")),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tên người nhận"),
                ),
                (
                    "facebook_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Facebook id",
                    ),
                ),
                (
                    "cach_xung_ho",
                    models.CharField(
                        max_length=255, verbose_name="Cách xưng hộ (cô/em)"
                    ),
                ),
                ("width_anh_goc", models.IntegerField(verbose_name="Width ảnh gốc")),
                (
                    "height_anh_goc",
                    models.IntegerField(default=1, verbose_name="Height ảnh gốc"),
                ),
                ("resid", models.CharField(max_length=255, verbose_name="resId")),
                ("authkey", models.CharField(max_length=255, verbose_name="authkey")),
                (
                    "is_sended",
                    models.BooleanField(default=False, verbose_name="Đã gửi"),
                ),
                (
                    "nguoi_lien_quan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_nguoi_lien_quan",
                        to="weddings.person",
                        verbose_name="Người liên quan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportantDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=255, verbose_name="Tên ngày trọng đại"),
                ),
                ("ngay_dien_ra", models.DateField(verbose_name="Ngày diễn ra sự kiện")),
                (
                    "thoi_gian_bat_dau",
                    models.TimeField(verbose_name="Thời gian bắt đầu"),
                ),
                (
                    "thoi_gian_ket_thuc",
                    models.TimeField(verbose_name="Thời gian kết thúc"),
                ),
                (
                    "dia_diem",
                    models.CharField(max_length=255, verbose_name="Địa điểm tổ chúc"),
                ),
                (
                    "map_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Đường dẫn google map",
                    ),
                ),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=weddings.utils.luu_anh_theo_ten,
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "gioi_thieu",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Giới thiệu nội dung buổi lễ",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weddings.wedding",
                        verbose_name="Lễ cưới",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ngày trọng đại",
                "ordering": ["ngay_dien_ra"],
            },
        ),
    ]
